server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/dressmart
    username: nilupulee
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enable: true
    user: nilupulee
    password: 12345
    baseline-description: "init"
    baseline-version: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: niluwats@gmail.com
    password: dyjtnzjmeyjdzzpf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


verification:
  email-verification-expiration: 15

security:
  jwt:
    secret-key: 0c7a60c5ab82db29b8c352c0d61738f3c295ea372e8d839ba919c99e6d7a3d6e
    expiration-time: 86400000