name: Build and Deploy dressmart app

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-deploy:
    name: Build and Deploy dressmart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
#          cache: gradle

#      - name: Grant execution permissions to Gradle wrapper
#        run: chmod +x ./gradlew
#
#      - name: Unit tests
#        run: ./gradlew test

      - name: Build the application
        run: |
          ./gradlew clean
          
          ./gradlew build
