name: Build and Deploy dressmart app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy dressmart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit tests
        run: ./gradlew test

      - name: Build the application
        run: |
          ./gradlew clean
          ./gradlew build
